import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, LoaderCircle } from "lucide-react";
import { useParams } from "react-router-dom";
import { createPublicBooking, fetchPublicBookingConfig, fetchPublicBookingSlots } from "../services/publicBooking";
import "./PublicBookingPage.css";

const today = () => new Date().toISOString().slice(0, 10);

export default function PublicBookingPage() {
  const { slug = "zantua" } = useParams();
  const [config, setConfig] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [slots, setSlots] = useState([]); const [loadingSlots, setLoadingSlots] = useState(false); const [saving, setSaving] = useState(false); const [confirmation, setConfirmation] = useState(null);
  const [form, setForm] = useState({ serviceId: "", specialistId: "", date: today(), startTime: "", firstName: "", lastName: "", phone: "", email: "" });
  useEffect(() => { let active = true; setLoading(true); fetchPublicBookingConfig(slug).then((data) => { if (active) setConfig(data); }).catch((loadError) => active && setError(loadError.message || "No fue posible cargar las reservas.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [slug]);
  useEffect(() => { let active = true; setForm((current) => ({ ...current, startTime: "" })); fetchPublicBookingSlots({ slug, serviceId: form.serviceId, specialistId: form.specialistId, date: form.date }).then((data) => active && setSlots(data)).catch((slotError) => active && setError(slotError.message || "No fue posible cargar los horarios.")).finally(() => active && setLoadingSlots(false)); if (form.serviceId && form.specialistId && form.date) setLoadingSlots(true); else setSlots([]); return () => { active = false; }; }, [slug, form.serviceId, form.specialistId, form.date]);
  const selectedService = useMemo(() => config?.services?.find((item) => item.id === form.serviceId), [config, form.serviceId]);
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setError(""); if (!form.startTime) return setError("Selecciona un horario disponible."); setSaving(true); try { const bookingId = globalThis.crypto?.randomUUID?.() || undefined; const data = await createPublicBooking({ ...form, slug, bookingId }); setConfirmation(data); } catch (submitError) { setError(submitError.message || "No fue posible confirmar la reserva."); } finally { setSaving(false); } };
  if (loading) return <main className="booking-page booking-state"><LoaderCircle className="booking-spin" /> Cargando reservas...</main>;
  if (error && !config) return <main className="booking-page booking-state"><h1>No fue posible cargar las reservas.</h1><p>{error}</p><button onClick={() => window.location.reload()}>Reintentar</button></main>;
  if (!config?.enabled || config?.not_found) return <main className="booking-page booking-state"><h1>Centro no encontrado</h1><p>Este enlace de reservas no está disponible.</p></main>;
  if (confirmation) return <main className="booking-page booking-state"><CheckCircle2 size={48} /><h1>Tu cita fue reservada</h1><p>Te esperamos el {confirmation.appointment_date} a las {confirmation.start_time}.</p></main>;
  return <main className="booking-page"><section className="booking-shell"><header className="booking-header"><img src={config.logo_url || "/Logo.jpg"} alt="Zantua Aesthetic Wellness" /><div><span>Reserva online</span><h1>{config.business_name || "Zantua Aesthetic Wellness"}</h1><p>Selecciona tu servicio, especialista y horario.</p></div></header><form className="booking-form" onSubmit={submit}>{error ? <div className="booking-error">{error}</div> : null}<label>Servicio<select required value={form.serviceId} onChange={update("serviceId")}><option value="">Selecciona un servicio</option>{(config.services || []).map((service) => <option key={service.id} value={service.id}>{service.name} · {service.duration_minutes || 40} min</option>)}</select></label><label>Especialista<select required value={form.specialistId} onChange={update("specialistId")}><option value="">Selecciona una especialista</option>{(config.specialists || []).map((specialist) => <option key={specialist.id} value={specialist.id}>{specialist.full_name}</option>)}</select></label><label>Fecha<input required type="date" min={today()} value={form.date} onChange={update("date")} /></label>{selectedService ? <p className="booking-summary"><Clock3 size={16} /> Duración estimada: {selectedService.duration_minutes || 40} minutos</p> : null}<div className="booking-slots"><strong><CalendarDays size={16} /> Horarios disponibles</strong>{loadingSlots ? <p>Cargando horarios...</p> : slots.length === 0 ? <p>{form.serviceId && form.specialistId ? "No hay horarios disponibles para esta fecha." : "Selecciona servicio, especialista y fecha."}</p> : <div>{slots.map((slot) => <button type="button" key={slot.start_time} className={form.startTime === slot.start_time ? "selected" : ""} onClick={() => setForm((current) => ({ ...current, startTime: slot.start_time }))}>{slot.start_time}</button>)}</div>}</div><div className="booking-patient"><label>Nombre<input required value={form.firstName} onChange={update("firstName")} /></label><label>Apellido<input required value={form.lastName} onChange={update("lastName")} /></label><label>Teléfono<input required inputMode="tel" value={form.phone} onChange={update("phone")} /></label><label>Correo (opcional)<input type="email" value={form.email} onChange={update("email")} /></label></div><button className="booking-submit" disabled={saving}>{saving ? "Confirmando..." : "Confirmar cita"}</button></form></section></main>;
}
